### ISSUE TITLE
Some questions about paper and code implement

### ISSUE THREAD

**Issue by SnaKey0u0** [xianlin7/SAMCT#2]
Dear author:

Thanks for the great work, It is very nice!

But I have some questions that I'd like to ask you. I hope you can find some time to respond amidst your busy schedule.

1. Figure 2 in the paper depicts that both Ftrans and Fcnns possess a window-partition-like design. However, in the code, I only found that Fcnns implement this design. Do the attention mechanisms in CNN2Trans and Trans2CNN operate with windowed Fcnns and global Ftrans?
https://github.com/xianlin7/SAMCT/blob/6d2d0d567ead36bfd513d459fa517f7a5228eefa/models/segment_anything_samct/modeling/image_encoder.py#L627-L632

2. What does "Close 1" mean in Figure 2 (b), and how does it function? Does it correspond to the following code?
https://github.com/xianlin7/SAMCT/blob/6d2d0d567ead36bfd513d459fa517f7a5228eefa/models/segment_anything_samct/modeling/image_encoder.py#L732

3. Can I take AutoPromptEncoder as a way that calculate L1 loss between its output and self.point_embeddings in original SAM prompt encoder? And why is the comment says that the loss can only use for Brats task?

4. In training stage, the sparse_embedding from original prompt encoder is never used, always use the output of AutoPromptEncoder and make it predict embedding better during the iteration, am I right?

Thank you again, I look forward to your response.

Best Regards

**Comment by xianlin7** [comment]
> Dear author:
> 
> Thanks for the great work, It is very nice!
> 
> But I have some questions that I'd like to ask you. I hope you can find some time to respond amidst your busy schedule.
> 
> 1. Figure 2 in the paper depicts that both Ftrans and Fcnns possess a window-partition-like design. However, in the code, I only found that Fcnns implement this design. Do the attention mechanisms in CNN2Trans and Trans2CNN operate with windowed Fcnns and global Ftrans?
>    https://github.com/xianlin7/SAMCT/blob/6d2d0d567ead36bfd513d459fa517f7a5228eefa/models/segment_anything_samct/modeling/image_encoder.py#L627-L632
> 2. What does "Close 1" mean in Figure 2 (b), and how does it function? Does it correspond to the following code?
>    https://github.com/xianlin7/SAMCT/blob/6d2d0d567ead36bfd513d459fa517f7a5228eefa/models/segment_anything_samct/modeling/image_encoder.py#L732
> 3. Can I take AutoPromptEncoder as a way that calculate L1 loss between its output and self.point_embeddings in original SAM prompt encoder? And why is the comment says that the loss can only use for Brats task?
> 4. In training stage, the sparse_embedding from original prompt encoder is never used, always use the output of AutoPromptEncoder and make it predict embedding better during the iteration, am I right?
> 
> Thank you again, I look forward to your response.
> 
> Best Regards
Thanks for your interest in SAMCT. I hope the following reply will be helpful to you.
1. The resolutions of Fcnn and Ftrans are generally different, and each position in Ftrans corresponds to the k × k window region in Fcnn (CNN branch contains more detailed features). As shown in Fig.2, when building information flows, we operate on patch-window pairs, where the patch is from each position of Ftrans, and the window is from the corresponding region of Fcnn.
2. As described in Page 4, "close 1" is a normalization operation to normalize the value to (0.5, 1.5). This operation is to appropriately enhance or suppress the attention of each position when refining the coarse attention map.
3. We hope the output prompt embeddings of the task-indicator prompt encoder can equal the prompt embeddings generated by the manual prompt. "self.point_embeddings in the original SAM prompt encoder" are not the prompt embeddings generated by the manual prompt, but the embeddings used to indicate the prompt types. Sorry, I don't understand what "And why is the comment says that the loss can only use for Brats task?" means.
4. Yes,  to make the model support work without manual prompts,  in AutoSAMCT, we only use the prompt embeddings generated by the Auto prompt encoder.
Best wishes.

**Comment by SnaKey0u0** [comment]
Regarding the third point, "And why is the comment says that the loss can only use for Brats task?" is from the following reference:

https://github.com/xianlin7/SAMCT/blob/6d2d0d567ead36bfd513d459fa517f7a5228eefa/utils/loss_functions/sam_loss.py#L198-L209

Thanks again for your reply!

Best Regards.

**Comment by xianlin7** [comment]
> Regarding the third point, "And why is the comment says that the loss can only use for Brats task?" is from the following reference:
> 
> https://github.com/xianlin7/SAMCT/blob/6d2d0d567ead36bfd513d459fa517f7a5228eefa/utils/loss_functions/sam_loss.py#L198-L209
> 
> Thanks again for your reply!
> 
> Best Regards.

These explanations were accidentally left behind, you can ignore them. 
Thank you for carefully reading our code. I will remove these redundant and misleading explanations in future versions.

**Comment by SnaKey0u0** [comment]
OK! Thank you!
